export { default as hightText } from './hightText';
export { default as removeHight } from './removeHight';
export { default as removeHights } from './removeHights';
export { default as showHight } from './showHight';
export { default as getHights } from './getHights';
// export { default as getLeveledHights } from './getLeveledHights';
export { default as getLostHights } from './getLostHights';
export { default as changeColor } from './changeColor';
export { default as editColor } from './editColor';
export { default as getCurrentColor } from './getCurrentColor';
export { default as getColorOptions } from './getColorOptions';
export { default as loadPageHights } from './loadPageHights';
export { default as toggleHighterCursor } from './toggleHightCursor';
